apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-memcached-policy
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.appName }} # Применяем правило к нашему Memcached
  policyTypes:
  - Ingress # Контролируем входящий трафик
  ingress:
  - from:
    - podSelector:
        matchLabels:
          role: backend # Разрешаем доступ ТОЛЬКО подам с лейблом role: backend
    ports:
    - protocol: TCP
      port: {{ .Values.service.targetPort }} # Порт 11211